version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P YourStrong!Passw0rd123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  companiesregistry.api:
    build:
      context: .
      dockerfile: CompaniesRegistry.Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__Database=Server=sqlserver,1433;Database=companies-registry;User Id=sa;Password=YourStrong!Passw0rd123;TrustServerCertificate=True;MultipleActiveResultSets=true;
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge
